/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePagination: typeof import('./src/components/TablePagination.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheLoading: typeof import('./src/components/TheLoading.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TruckForm: typeof import('./src/components/TruckForm.vue')['default']
  }
}
